### ISSUE TITLE
SMILES preprocessing violation

### ISSUE THREAD

**Issue by wangbenwang123** [BenderGroup/PIDGINv4#4]
when I executing predict.py, I encounter this error:
SMILES preprocessing violation (line 1 will be removed): CC(C)CC(C(=O)NC(CC(=O)O)C(=O)NC(CO)C(=O)O)NC(=O)C(C(C)C)NC(=O)C(CCCCN)NC(=O)C(CCCCN)NC(=O)C(CCSC)NC(=O)C(CCC(=O)N)NC(=O)C(CCSC)N

I want to know why this problem occurs and how to solve it.

**Comment by laylagerami** [comment]
Hello,

Sorry for the delayed response.

It looks like you have input a peptide for prediction with PIDGINv4. PIDGINv4 was trained on small drug-like molecules so the models will not be reliable for entities which look significantly dissimilar to the training set (e.g., biologics). 

For this reason, pre-processing is performed and SMILES which don't pass the filters are removed. This can be bypassed with the `--preprocess_off` flag (see https://pidginv4.readthedocs.io/en/latest/usage/command.html) although it is not recommended.

> Turning off pre-processing (–preprocess_off)
PIDGINv4 implements a pre-processing feature which is turned on by default, to ensure all input molecules are standardised using the flatkinson (eTox) standardiser (github.com/flatkinson/standardiser), and that any molecules outside the applicability domain of the models, defined by the chemical property filters imposed on ChEMBL and PubChem training data [size filter 100 >= Mw >= 1000 / organic mol check (Carbon count >= 1)] are removed. This functionality can be turned off to force PIDGINv4 to give unreliable predictions (in cases when the input space maybe outside the domain of applicability or when molecules have been pre-standardised) using the following command:
> --preprocess_off


We recommend that you use a tool which is specifically aimed at biologics rather than relying on the predictions of PIDGINv4 for this peptide.
